version: '3.7'

services:
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTEGRES_DB: minekosan_development