version: '3.7'

services:
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: minekosan_development
    ports:
      - 5432:5432